### ISSUE TITLE
[IDEA] Pacman template

### ISSUE THREAD

**Issue by e-minguez** [jameslabocki/scholarshift#3]
Based on [pacman-nodejs-app](https://github.com/font/k8s-example-apps/tree/master/pacman-nodejs-app) I created [this gist](https://gist.github.com/e-minguez/660683b04a5754402e5bb169a9005745) to easily import a template with the required stuff to run pacman in containers in OpenShift with just `oc create -f && oc new-app --template=pacman`

**Comment by jameslabocki** [comment]
Thanks! Just to let you know, I was able to make it run, but I had to delete the liveness and readiness checks. I also hard-coded the database connection string in the config.js as I wasn’t able to figure out how the environment variables worked for passing them in. I took a shortcut for now! :)
